# Notes dynamodb table

Resources:
  notesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: notes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: notesId
          AttributeType: S
      KeySchema:
        - AttributeName: notesId
          KeyType: HASH

  # Cognito user pool
  cognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyNotesUPD

  # User pool web client
  cognitoUserPoolWebclient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref cognitoUserPool
      ClientName: web
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid
      AllowedOAuthFlows:
        - implicit
      CallbackURLs:
        - http://localhost:3000

  # User pool domain
  cognitoUserPoolDoamin:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref cognitoUserPool
      Domain: my-notes-upd-test

  # Application parameters
  userPoolIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /notes/dev/userPoolId
      Type: String
      Value: !GetAtt cognitoUserPool.Arn
